<?

if (file_exists("setup/setup.phtml")):

	include("setup/setup.phtml");

	if (file_exists("$listadmin/$list.phtml")):

		include("$listadmin/$list.phtml");

		if (file_exists("$header.phtml")):
			include("$header.phtml");
		endif;
	
		echo "<center><br><br><br>";

		if ($enc != ""):
			if (file_exists("confirm/$enc")): $optout = "off"; include("confirm/$enc"); endif;
		endif;

		if (file_exists("$lists/$id.phtml")):

			exec("grep '$email' '$lists/$id.phtml'",$execAr);

			if ($execAr[0] == ""):

				echo "<center><br><br><br>This address is not on our list.";

			else:

				if ($optout == "on"):

					$enc = uniqid("");

					$to = "$email";
					$from = "$listname <$from>";
					$subject = "Unsubscribe Confirmation";
					$body = "To confirm your unsubscribe request please click the link below:\n$url/unsub.phtml?list=$list&enc=$enc\n\nIf you did not post an unsubscribe request please disregard this message and you will not be removed from the list.";
		
					mail($to,$subject,$body,"FROM: ".$from);

					$filemessage = "<? \$email = \"$email\"; ?>";
					$cartFile = fopen("confirm/$enc","w+");
					fputs($cartFile,$filemessage);
					fclose($cartFile);

					echo "<P>Thank you<P>A confirmation message has been sent to <b>$email</b><BR>Please check your mail to complete the unsubscribe process.";

				else:

					$count=0;
					$maxloop=5;
					$finished=0;
					while ($count<$maxloop&&!$finished) {
	
					if (file_exists("$lists/$id.phtml")):
	
						exec ("mv -f '$lists/$id.phtml' '$lists/$id.tmp'");
	
						exec("grep -v \"$email\" '$lists/$id.tmp' > '$lists/$id.phtml.tmp2'");
						exec("mv -f '$lists/$id.phtml.tmp2' '$lists/$id.tmp'");
	
						exec ("mv -f '$lists/$id.tmp' '$lists/$id.phtml'");
						$finished=1;
	
					else:
					
						sleep(1);
													
					endif;
					$count++;
					}
	
					echo "<P>We're sorry to see you go!<P><b>$email</b><BR>has been removed from our 	mailing list.";

				endif;			

			endif;

		else:

			echo "<P><b>Error!</b><BR>The list you are trying to susbcribe to does not exist";

		endif;

	else:

		echo "I'm sorry your address could not be removed from our list at this time.<BR>Please try again later.";

	endif;

else:

	echo "I'm sorry your address could not be added to our list at this time.<BR>Please try again later.";

endif;

echo "<BR><BR><BR><BR><font size=\"1\"><a href=\"http://www.webdrive.co.nz/php/mlm.phtml\" target=\"new\">Powered by MultiList Manager</a></font></center>";

if (file_exists("$footer.phtml")):
	include("$footer.phtml");
endif;

?>