<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<HTML>
<HEAD>
	<TITLE>PHPostcards 1.1</TITLE>
</HEAD>

<BODY BGCOLOR="#FFFFFF" TEXT="#000000" LINK="#0000FF" VLINK="#800080">

<TABLE WIDTH="90%" ALIGN="center">
<TR BGCOLOR="#00003E">
	<TD ALIGN="center"><FONT SIZE="+3" COLOR="#FFFFFF">PHP</FONT><FONT SIZE="+1" COLOR="#FFFFFF">ostcards 1.2</FONT></TD>
</TR>


<TR>
	<TD>
	
<P><BR><P><CENTER>
<!-- BEGIN RICH-MEDIA BURST! CODE --> 
      <script language="JavaScript"> 
      <!-- /* © 1997-1999 BURST! Media, LLC. All Rights Reserved.*/ 
      var TheAdcode = 'ad5122a'; 
      var bN = navigator.appName; 
      var bV = parseInt(navigator.appVersion); 
      var base='http://www.burstnet.com/'; 
      var Tv=''; 
      var agt=navigator.userAgent.toLowerCase(); 
      if (bV>=4) 
        {ts=window.location.pathname+window.location.search; 
         i=0; Tv=0; while (i< ts.length) 
            { Tv=Tv+ts.charCodeAt(i); i=i+1; } Tv="/"+Tv;} 
        else   {Tv=escape(window.location.pathname); 
         if( Tv.charAt(0)!='/' ) Tv="/"+Tv; 
                else if (Tv.charAt(1)=="/")
      Tv=""; 
        if( Tv.charAt(Tv.length-1) == "/") 
          Tv = Tv + "_";} 
      if (bN=='Netscape'){ 
           if ((bV>=4)&&(agt.indexOf("mac")==-1))
      {  document.write('<s'+'cript src="'+ 
            base+'cgi-bin/ads/'+TheAdcode+'.cgi/RETURN-CODE/JS' 
            +Tv+'">'); 
           document.write('</'+'script>');    
      } 
           else if (bV>=3) {document.write('<'+'a href="'+base+'ads/'+ 
              TheAdcode+'-map.cgi'+Tv+'"target=_top>'); 
              document.write('<img src="' + base + 'cgi-bin/ads/' + 
              TheAdcode + '.cgi' + Tv + '" ismap width=468 height=60' + 
              ' border=0 alt="Click Here"></a>');} 
       } 
      if (bN=='Microsoft Internet Explorer') 
       document.write('<ifr'+'ame id=BURST src="'+base+'cgi-bin/ads/'
      + 
        TheAdcode + '.cgi' + Tv + '/RETURN-CODE" width=468 height=60' + 
        'marginwidth=0 marginheight=0 hspace=0 vspace=0 ' + 
        'frameborder=0 scrolling=no></ifr'+'ame>'); 
      // --> 
      </script> 
      <noscript><a href="http://www.burstnet.com/ads/ad5122a-map.cgi" target=_top> 
      <img src="http://www.burstnet.com/cgi-bin/ads/ad5122a.cgi" 
       width=468 height=60 border=0 alt="Click Here"></a> 
      </noscript> 
      <!-- END BURST CODE -->
	  </CENTER>
	  <P><BR><P>